services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    environment:
      API_GATEWAY_PORT: ${API_GATEWAY_PORT}
      API_GATEWAY_USER: ${API_GATEWAY_USER}
      API_GATEWAY_PASSWORD: ${API_GATEWAY_PASSWORD}
      RATE_LIMIT_REQUESTS_PER_SECOND: ${RATE_LIMIT_REQUESTS_PER_SECOND}
      PORT1: ${PORT1}
      PORT2: ${PORT2}
    restart: always
    ports:
      - ${API_GATEWAY_PORT}:80

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    command: ["redis-server", "--loglevel", "verbose"]

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all"]

volumes:
  postgres_data: